### ISSUE TITLE
Uncaught server error: java.lang.NoSuchMethodError: 'org.jboss.resteasy.spi.ResteasyUriInfo org.jboss.resteasy.spi.HttpRequest.getUri()'

### ISSUE THREAD

**Issue by feraudet** [richardjkendall/login-with-email#4]
Hello,

On click on the email link I get a **We are sorry... An internal server error has occurred**

Here the stack trace.

Any idea ?

Thanks in advance

```
21:11:55,939 INFO  [com.richardjameskendall.keycloak.auth] (default task-37) Create users is enabled.
--
21:11:55,940 INFO  [com.richardjameskendall.keycloak.auth] (default task-37) Allowed domains found: xxx.com
21:11:55,940 INFO  [com.richardjameskendall.keycloak.auth] (default task-37) Email suffix on request: xxx.com
21:11:55,940 INFO  [com.richardjameskendall.keycloak.auth] (default task-37) Email suffix matches an allowed domain
21:12:09,060 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-37) Uncaught server error: java.lang.NoSuchMethodError: 'org.jboss.resteasy.spi.ResteasyUriInfo org.jboss.resteasy.spi.HttpRequest.getUri()'
at deployment.email-otp-spi-1.0-SNAPSHOT.war//com.richardjameskendall.keycloak.auth.EmailLinkAuthenticator.authenticate(EmailLinkAuthenticator.java:127)
at org.keycloak.keycloak-services@18.0.0//org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:460)
at org.keycloak.keycloak-services@18.0.0//org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:264)
at org.keycloak.keycloak-services@18.0.0//org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:395)
at org.keycloak.keycloak-services@18.0.0//org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:286)
at org.keycloak.keycloak-services@18.0.0//org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1030)
at org.keycloak.keycloak-services@18.0.0//org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:892)
at org.keycloak.keycloak-services@18.0.0//org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:323)
```

**Comment by richardjkendall** [comment]
It looks like it might be related to this issue:

https://issueantenna.com/repo/keycloak/keycloak/issues/10907

What version of keycloak are you testing against?

**Comment by richardjkendall** [comment]
@feraudet - I've been unable to replicate this error on the latest version of Keycloak (18.0.0) running on Wildfly.

Are you using the version which runs on Quarkus?  I'm not ready to migrate my deployments yet because my build/deploy process depends on some aspects of Wildfly.

Nevertheless, I have altered the code as recommended in the link I posted above.

**Comment by richardjkendall** [comment]
@feraudet - would appreciate if you can test the version in this branch and see if it resolves the issue for you.

**Comment by feraudet** [comment]
Hey @richardjkendall 
I tried with many version from https://quay.io/repository/keycloak/keycloak

> @feraudet - I've been unable to replicate this error on the latest version of Keycloak (18.0.0) running on Wildfly.
> 
> Are you using the version which runs on Quarkus? I'm not ready to migrate my deployments yet because my build/deploy process depends on some aspects of Wildfly.
> 
> Nevertheless, I have altered the code as recommended in the link I posted above.

**Comment by feraudet** [comment]
It work perfectly with a build from this branch !
```
FROM quay.io/keycloak/keycloak:18.0.0-legacy
COPY email-otp-spi-1.0-SNAPSHOT.war /opt/jboss/keycloak/standalone/deployments/
```
> @feraudet - would appreciate if you can test the version in this branch and see if it resolves the issue for you.

**Comment by richardjkendall** [comment]
Great.  I'll merge this fix
